"""Review prompts carry their output formats, generated by the writer.

Evidence gate (red-before-green):

- RED: ``write-prompt --review-kind planning|task-closure`` wrote only the
  PM-authored body plus the generated request-comparison sections. The
  reviewer received no review-file or review-report format and had to
  search the installed protocol and templates to discover them; the only
  remedy was a documented instruction for the PM to paste
  ``report-skeleton`` output, which the PM did not reliably follow, and no
  generator existed at all for planning-checkpoint reviews.
- GREEN: the writer appends two machine-owned sections — ``## Review file
  skeleton`` and ``## Review completion report skeleton`` — each naming its
  exact output path and carrying a fenced skeleton built by the same
  builders ``report-skeleton`` uses, filled with the identities of the
  request context the prompt binds. Rewriting replaces them; authored copies
  of the headings never survive. A reviewer who fills only the placeholders
  produces a review file and report that ``validate-report`` and
  ``report-action`` accept, and the request-context preflight is unchanged.
"""
from __future__ import annotations

import contextlib
import re
import unittest
from typing import Dict

from cli import request_trace
from cli.commands import report_action, report_skeleton, review_context, validate_report, write_prompt
from cli.markdown_fences import FenceTracker, opening_info
from tests.cli.test_generated_artifact_parity import _invoke
from tests.scaffold import project_scaffold
from tests.test_kickoff_readiness import _TOML_PLANNING_REVIEW, _capture, _isolated_home
from tests.test_review_bootstrap_parity import BootstrapFixture

FILE_HEADING = report_skeleton.REVIEW_FILE_SECTION_HEADING
REPORT_HEADING = report_skeleton.REVIEW_REPORT_SECTION_HEADING

# The reviewer's judgment for a clean approval, keyed by the placeholder the
# skeleton leaves for it. Every other `<...>` placeholder line is prose.
_JUDGMENT = {
    "Status: <complete | blocked | failed>": "Status: complete",
    "Request alignment: <aligned | drifted>": "Request alignment: aligned",
    "Verdict: <approve | request-changes | reject>": "Verdict: approve",
    "<approve | request-changes | reject>": "approve",
    "Reviewer: <free text>": "Reviewer: configured reviewer",
    "Outcome: <adequate | needs changes>": "Outcome: adequate",
}


def _fill(skeleton: str) -> str:
    lines = []
    for line in skeleton.splitlines():
        if line in _JUDGMENT:
            line = _JUDGMENT[line]
        elif re.fullmatch(r"<.*>", line.strip()):
            line = "none."
        lines.append(line)
    filled = "\n".join(lines) + "\n"
    assert "<" not in filled.replace("<-", ""), filled
    return filled


def _sections(prompt: str) -> Dict[str, str]:
    """Each generated section's single fenced skeleton, by heading."""
    found: Dict[str, str] = {}
    tracker = FenceTracker()
    current = None
    block = None
    for line in prompt.splitlines():
        was_in_fence = tracker.in_fence
        is_delimiter = tracker.feed(line)
        if not was_in_fence and not is_delimiter and line.startswith("## "):
            current = line
            continue
        if current in (FILE_HEADING, REPORT_HEADING):
            if is_delimiter and not was_in_fence:
                assert opening_info(line) == "text"
                block = []
            elif is_delimiter and was_in_fence:
                assert current not in found, f"duplicate skeleton under {current}"
                found[current] = "\n".join(block) + "\n"
                block = None
            elif block is not None:
                block.append(line)
    return found


def _heading_count(prompt: str, heading: str) -> int:
    tracker = FenceTracker()
    count = 0
    for line in prompt.splitlines():
        was_in_fence = tracker.in_fence
        if not tracker.feed(line) and not was_in_fence and line == heading:
            count += 1
    return count


class _PlanningFixture(unittest.TestCase):
    checkpoint = "PLAN-BUILD-01-005"

    def setUp(self) -> None:
        stack = contextlib.ExitStack()
        self.addCleanup(stack.close)
        stack.enter_context(_isolated_home())
        scaffold = stack.enter_context(project_scaffold(cartopian_toml=_TOML_PLANNING_REVIEW))
        self.root = scaffold.project_root
        _capture(self.root, "Build the scoped feature.", record_id="REQUEST-001", sequence=0)
        scaffold.write("tasks/open/TASK-01-005.md", "Phase: PHASE-01\nPlan ref: BUILD-01-005\n")
        scaffold.write("specs/SPEC-01-005.md", "# Spec\n")
        self.prompt = self.root / f"prompts/PROMPT-{self.checkpoint}.md"
        self.review = self.root / f"reviews/REVIEW-{self.checkpoint}.md"
        self.report = self.root / f"reports/REPORT-{self.checkpoint}.md"

    def write(self, content: str = "# Review\n\n## Your role\nReview this scope.\n"):
        code, records, err = _invoke(
            write_prompt.handler, project_root=str(self.root),
            prompt_id="PROMPT-" + self.checkpoint, content=content,
            content_file=None, review_kind="planning", task=None,
            checkpoint=self.checkpoint, phase="PHASE-01", plan_ref="BUILD-01-005",
        )
        self.assertEqual(code, 0, err)
        return records, self.prompt.read_text(encoding="utf-8")

    def preflight(self):
        return _invoke(
            review_context.handler, project_root=str(self.root),
            review_kind="planning", task=None, checkpoint=self.checkpoint,
            phase=None, plan_ref=None, prompt=str(self.prompt),
        )



class PlanningReviewPromptSkeletonTests(_PlanningFixture):
    def test_prompt_carries_both_skeletons_bound_to_its_context(self) -> None:
        _records, prompt = self.write()
        for heading in (FILE_HEADING, REPORT_HEADING):
            self.assertEqual(_heading_count(prompt, heading), 1, heading)
        # The skeletons follow every other generated section.
        self.assertLess(
            prompt.index(request_trace.MANAGEMENT_SECTION_HEADING), prompt.index(FILE_HEADING)
        )
        self.assertLess(prompt.index(FILE_HEADING), prompt.index(REPORT_HEADING))
        self.assertIn(f"Write the review file first, to: {self.review.resolve()}", prompt)
        self.assertIn(f"Write the review completion report last, to: {self.report.resolve()}", prompt)

        code, records, err = self.preflight()
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["preflight"]["ok"])
        identity = records[0]["context_identity"]

        skeletons = _sections(prompt)
        review, report = skeletons[FILE_HEADING], skeletons[REPORT_HEADING]
        for text in (review, report):
            self.assertIn(f"Request-context identity: {identity}", text.splitlines())
            self.assertIn("Request evidence: REQUEST-001", text.splitlines())
        self.assertTrue(review.startswith(f"# REVIEW-{self.checkpoint}\n"))
        for line in (
            f"Target: {self.checkpoint}",
            "Planning stage: tasks-and-specs",
            "Phase: PHASE-01",
            "Plan ref: BUILD-01-005",
        ):
            self.assertIn(line, review.splitlines())
        self.assertTrue(report.startswith(f"# REPORT-{self.checkpoint}\n"))
        self.assertIn(f"- Prompt path: {self.prompt.resolve()}", report.splitlines())
        self.assertIn(f"- Review file path: {self.review.resolve()}", report.splitlines())
        # Bounded: skeletons, not templates or protocol text.
        self.assertNotIn("## Contract quality", prompt)
        self.assertNotIn("Redaction reminder", prompt)

    def test_filled_skeletons_validate_and_route(self) -> None:
        _records, prompt = self.write()
        skeletons = _sections(prompt)
        self.review.write_text(_fill(skeletons[FILE_HEADING]), encoding="utf-8")
        self.report.write_text(_fill(skeletons[REPORT_HEADING]), encoding="utf-8")

        code, records, err = _invoke(
            validate_report.handler, report_path=str(self.report),
            variant=None, expected_identity=None,
        )
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["ok"], records[0]["checks"])
        self.assertEqual(records[0]["variant"], "planning-review")

        code, records, err = _invoke(
            report_action.handler, report_path=str(self.report), variant=None,
            expected_identity=None, expected_review_identity=None,
        )
        self.assertEqual(code, 0, err)
        self.assertEqual(records[0]["verdict"], "accepted")

    def _request_changes(self, findings: str) -> None:
        skeletons = _sections(self.write()[1])
        review = _fill(skeletons[FILE_HEADING]).replace(
            "Verdict: approve", "Verdict: request-changes"
        )
        head, _, _ = review.partition("## Findings")
        rest = review.partition("## Findings")[2].partition("## Suggested actions")[2]
        self.review.write_text(
            f"{head}## Findings\n\n{findings}\n\n## Suggested actions{rest}",
            encoding="utf-8",
        )
        self.report.write_text(
            _fill(skeletons[REPORT_HEADING]).replace("\napprove\n", "\nrequest-changes\n"),
            encoding="utf-8",
        )

    def _findings_check(self) -> dict:
        code, records, err = _invoke(
            validate_report.handler, report_path=str(self.report),
            variant=None, expected_identity=None,
        )
        return {c["name"]: c for c in records[0]["checks"]}["review-findings-projectable"]

    def test_request_changes_without_finding_rows_fails_the_self_check(self) -> None:
        self._request_changes("The plan needs work in several places.")
        check = self._findings_check()
        self.assertFalse(check["pass"], check)
        self.assertEqual(check["failure_class"], "substantive")
        self.assertIn("handoff prompt", check["recovery"])

    def test_request_changes_with_finding_rows_passes_and_projects(self) -> None:
        self._request_changes(
            "- F1. [major] — TASK-01-005 lacks an acceptance check; add one."
        )
        self.assertTrue(self._findings_check()["pass"])
        code, records, err = _invoke(
            report_action.handler, report_path=str(self.report), variant=None,
            expected_identity=None, expected_review_identity=None,
        )
        self.assertEqual(code, 0, err)
        self.assertEqual(
            records[0]["review_projection"]["findings"],
            ["- F1. [major] — TASK-01-005 lacks an acceptance check; add one."],
        )

    def test_rewrite_replaces_generated_and_authored_copies(self) -> None:
        _records, first = self.write()
        authored = (
            "# Review\n\n## Your role\nReview this scope.\n\n"
            f"{REPORT_HEADING}\n\nPM-pasted stale report skeleton.\n\n"
            "```text\n# REPORT-PLAN-STALE\n\n## Verdict\n\napprove\n```\n\n"
            "## Scope notes\n\nKeep this authored note.\n"
        )
        _records, rewritten = self.write(authored)
        self.assertNotIn("PM-pasted stale report skeleton", rewritten)
        self.assertNotIn("REPORT-PLAN-STALE", rewritten)
        self.assertIn("Keep this authored note.", rewritten)
        for heading in (FILE_HEADING, REPORT_HEADING):
            self.assertEqual(_heading_count(rewritten, heading), 1, heading)

        # Rewriting the written prompt itself is idempotent for the
        # generated sections and keeps the binding current.
        _records, again = self.write(first)
        for heading in (FILE_HEADING, REPORT_HEADING):
            self.assertEqual(_heading_count(again, heading), 1, heading)
        self.assertEqual(_sections(again), _sections(first))
        self.assertEqual(
            again[again.index(FILE_HEADING):], first[first.index(FILE_HEADING):]
        )
        code, records, err = self.preflight()
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["preflight"]["ok"])


class LegacyCounterCheckpointTests(_PlanningFixture):
    """A counter checkpoint carries only its explicitly declared scope."""

    checkpoint = "PLAN-015"

    def test_declared_scope_fills_and_undeclared_stays_placeholder(self) -> None:
        _records, prompt = self.write(
            "# Review\n\nPlanning stage: tasks-and-specs\n\n## Your role\nReview.\n"
        )
        review = _sections(prompt)[FILE_HEADING].splitlines()
        self.assertIn("Target: PLAN-015", review)
        self.assertIn("Planning stage: tasks-and-specs", review)
        # Supplied by --phase / --plan-ref because the body declared neither.
        self.assertIn("Phase: PHASE-01", review)
        self.assertIn("Plan ref: BUILD-01-005", review)

        _records, prompt = self.write("# Review\n\n## Your role\nReview.\n")
        review = _sections(prompt)[FILE_HEADING].splitlines()
        self.assertIn(
            "Planning stage: <requirements-and-standards | implementation-plan "
            "| phases | tasks-and-specs>",
            review,
        )


class TaskClosureReviewPromptSkeletonTests(BootstrapFixture):
    def setUp(self) -> None:
        super().setUp()
        self.move_to_review()
        self.prompt = self.root / "prompts/PROMPT-07-001.md"
        self.review = self.root / "reviews/REVIEW-07-001.md"
        self.review_report = self.root / "reports/REPORT-07-001-review.md"

    def write(self, body: str = "# Review task completion\n") -> str:
        code, _records, err = self.run_cli(
            "write-prompt", str(self.root), "--prompt-id", "PROMPT-07-001",
            "--review-kind", "task-closure", "--task", str(self.task),
            "--content", body,
        )
        self.assertEqual(code, 0, err)
        return self.prompt.read_text(encoding="utf-8")

    def test_prompt_carries_the_shared_review_skeletons(self) -> None:
        prompt = self.write()
        for heading in (FILE_HEADING, REPORT_HEADING):
            self.assertEqual(_heading_count(prompt, heading), 1, heading)
        self.assertIn(f"Write the review file first, to: {self.review.resolve()}", prompt)
        self.assertIn(
            f"Write the review completion report last, to: {self.review_report.resolve()}",
            prompt,
        )

        code, records, err = self.run_cli(
            "review-context", str(self.root), "--review-kind", "task-closure",
            "--task", str(self.task), "--prompt", str(self.prompt),
        )
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["preflight"]["ok"])
        context = request_trace.context_for_task(
            self.root, self.task, prompt_text=prompt, require_completion_evidence=True
        )
        expected = report_skeleton.task_review_skeletons(
            self.root, self.task.resolve(), self.task.read_text(encoding="utf-8"),
            report_skeleton.bindings_from_context(context),
        )
        skeletons = _sections(prompt)
        # Byte-identical to the shared builder report-skeleton uses.
        self.assertEqual(skeletons[FILE_HEADING], expected["review_file_skeleton"])
        self.assertEqual(skeletons[REPORT_HEADING], expected["skeleton"])
        self.assertIn(
            f"Request-context identity: {context.context_identity}",
            skeletons[REPORT_HEADING].splitlines(),
        )

        # Handoff preflight still admits the prompt.
        code, records, err = self.run_cli("handoff-packet", str(self.task), "--role", "reviewer")
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["request_trace"]["preflight"]["ok"])
        self.assertTrue(records[0]["input_payload_audit"]["ok"])

    def test_filled_skeletons_validate_and_route(self) -> None:
        skeletons = _sections(self.write())
        self.review.write_text(_fill(skeletons[FILE_HEADING]), encoding="utf-8")
        self.review_report.write_text(_fill(skeletons[REPORT_HEADING]), encoding="utf-8")
        code, records, err = self.run_cli("validate-report", str(self.review_report))
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["ok"], records[0]["checks"])
        code, records, err = self.run_cli("report-action", str(self.review_report))
        self.assertEqual(code, 0, err)
        self.assertEqual(records[0]["verdict"], "accepted")

    def test_rewrite_keeps_one_copy_of_each_section(self) -> None:
        first = self.write()
        again = self.write(first)
        for heading in (FILE_HEADING, REPORT_HEADING):
            self.assertEqual(_heading_count(again, heading), 1, heading)
        # A task-closure rewrite takes a fresh management snapshot (the
        # prompt itself now exists), so the context identity may move; the
        # skeletons always follow the identity the rewritten prompt binds.
        bound = request_trace.extract_request_sections(again)
        identity_line = next(
            line for line in bound.splitlines()
            if line.startswith("Request-context identity:")
        )
        for skeleton in _sections(again).values():
            self.assertIn(identity_line, skeleton.splitlines())
        code, records, err = self.run_cli(
            "review-context", str(self.root), "--review-kind", "task-closure",
            "--task", str(self.task), "--prompt", str(self.prompt),
        )
        self.assertEqual(code, 0, err)
        self.assertTrue(records[0]["preflight"]["ok"])


class StripGeneratedSectionsTests(unittest.TestCase):
    def test_fenced_headings_do_not_end_the_section(self) -> None:
        text = (
            "# Prompt\n\nAuthored.\n\n"
            f"{FILE_HEADING}\n\n````text\n# REVIEW-X\n\n## Summary\n\n```\nnested\n```\n````\n\n"
            f"{REPORT_HEADING}\n\n```text\n## Verdict\n```\n\n"
            "## Authored tail\n\nKept.\n"
        )
        stripped = report_skeleton.strip_review_prompt_sections(text)
        self.assertEqual(stripped, "# Prompt\n\nAuthored.\n\n## Authored tail\n\nKept.\n")

    def test_text_without_generated_sections_is_unchanged(self) -> None:
        text = "# Prompt\n\n## Your role\nReview.\n"
        self.assertIs(report_skeleton.strip_review_prompt_sections(text), text)


class PlanningScopeLinesTests(unittest.TestCase):
    def skeleton(self, scope, legacy=False):
        bindings = {"evidence": "none", "context_identity": "sha256:" + "0" * 64, "legacy": legacy}
        return report_skeleton.planning_review_skeletons(
            "/tmp/proj", "PLAN-001", bindings, scope=scope
        )

    def test_undeclared_legacy_scope_stays_a_placeholder(self) -> None:
        review = self.skeleton({"stage": None, "phase": None, "plan_ref": None})["review_file_skeleton"]
        self.assertIn(
            "Planning stage: <requirements-and-standards | implementation-plan | phases | tasks-and-specs>",
            review,
        )
        self.assertIn("Phase: <PHASE-NN | n/a>", review)
        self.assertIn("Plan ref: <KIND-NN-NNN | n/a>", review)

    def test_declared_scope_is_filled_and_inapplicable_scope_is_na(self) -> None:
        review = self.skeleton(
            {"stage": "requirements-and-standards", "phase": None, "plan_ref": None}
        )["review_file_skeleton"]
        self.assertIn("Planning stage: requirements-and-standards", review)
        self.assertIn("Phase: n/a", review)
        self.assertIn("Plan ref: n/a", review)

    def test_legacy_context_offers_only_acceptable_alignment(self) -> None:
        built = self.skeleton({"stage": "phases", "phase": "PHASE-02", "plan_ref": None}, legacy=True)
        for text in (built["skeleton"], built["review_file_skeleton"]):
            self.assertIn("Request alignment: <unavailable-for-legacy | drifted>", text)
        self.assertIn("Plan ref: n/a", built["review_file_skeleton"])


if __name__ == "__main__":
    unittest.main()
