"""Deterministic, standard-library evaluation foundation."""

from evaluations.runner import (
    AggregateResult,
    AmbiguousJsonError,
    CaseResult,
    Diagnostic,
    EvaluationCase,
    EvaluationRegistry,
    ExpectedOutcome,
    InputSpec,
    MeasurementBoundary,
    ObservedResult,
    SelectionError,
    ValidationError,
    ValidationIssue,
    discover_cases,
    load_json_document,
    render_human,
    render_machine,
    run_cases,
    select_cases,
)

__all__ = [
    "AggregateResult",
    "AmbiguousJsonError",
    "CaseResult",
    "Diagnostic",
    "EvaluationCase",
    "EvaluationRegistry",
    "ExpectedOutcome",
    "InputSpec",
    "MeasurementBoundary",
    "ObservedResult",
    "SelectionError",
    "ValidationError",
    "ValidationIssue",
    "discover_cases",
    "load_json_document",
    "render_human",
    "render_machine",
    "run_cases",
    "select_cases",
]
